# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20180323_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='content',
            field=models.CharField(default='To be added', max_length=255),
            preserve_default=False,
        ),
    ]
